### ISSUE TITLE
Auto bump type not yet supported

### ISSUE THREAD

**Issue by aaronsteers** [meltano/commitizen-version-bump#4]
https://github.com/meltano/sdk/runs/8260371957?check_suite_focus=true

```
'cz_version_bump' rule does not support bump
```

https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/bump.py#L81

I don't think this is necessarily a high pri and definitely not high urgency. Error occured when I selected `auto` for bump type, but the easy fix is just to select `minor` - which is generally most relevant anyway.

Normally semver rules probably aren't correct for us. I think `major` versions should only get published on explicit request, so it would be just a question of whether the release is `patch` or `minor`.

**Comment by WillDaSilva** [comment]
We should probably just disable the use of `auto` altogether. Forcing the user to select which part of the version is being bumped seems appropriate. They should always know, and anything else could lead to surprises.

**Comment by aaronsteers** [comment]
Looks like this is working as expected. Job correctly chose `patch` when only fixes were included:

- https://github.com/meltano/meltano/pull/6749
