### ISSUE TITLE
Name exclusion for team members not yet working

### ISSUE THREAD

**Issue by aaronsteers** [meltano/commitizen-version-bump#6]
This is not necessarily high pri and not high urgency.

The auto-changelog for Meltano is adding thanks for team members.

## Mitigation

The mitigation is fast and easy: simply delete "thanks" entries for team members.

**Comment by aaronsteers** [comment]
From https://github.com/meltano/meltano/pull/6736/files?short_path=06572a9#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed


<details>
<summary>Details</summary>

<img width="926" alt="image" src="https://user-images.githubusercontent.com/18150651/189241985-bf2db5f0-212d-4fe3-8c8b-814964e4a374.png">


</details>

**Comment by WillDaSilva** [comment]
This would only happen if the token being used in CI does not have the proper credentials. We will have to update the workflows to use the Meltybot key if they are not already, and if they are, update the Meltybot key to be able to read org members.

**Comment by WillDaSilva** [comment]
This should now be resolved for Meltano and the SDK. Seems like the GitHub API key not having read:org permissions was the culprit. I'll wait till one of them has a few more contributions with which to make a release PR, and then verify that it's not thanking the Meltano team members.

**Comment by aaronsteers** [comment]
Thanks, @WillDaSilva !

**Comment by aaronsteers** [comment]
Looks like this is working as expected now:

- Output of test run: https://github.com/meltano/meltano/pull/6749
